intent_patterns:
  high_youtube_confidence:
    - trailer
    - review
    - analysis
    - behind the scenes
    - comparison
    - reaction
    - fan theories
    - fan theory
    - discussion
    - discussions
    - youtuber
    - youtubers
    - youtube suggestions
    - youtube recommendation
    - famous youtubers
  medium_youtube_confidence:
    - explain
    - breakdown
    - guide
    - tutorial
  youtube_search_optimization:
    trailer: "official trailer"
    review: "review analysis"
    behind_scenes: "behind the scenes"
    fan_discussion: "fan theories discussion"
    youtuber_recommendation: "youtuber recommendations"
