data:
  categories:
  - anime
  - manga
  - bollywood
  - hollywood
  - kdrama
  - kmovie
  preprocessing:
    chunk_overlap: 50
    chunk_size: 512
    embedding_stats_file: embedding_stats.json
    log_file: preprocess_log.txt
    metadata_file: metadata.json
    output_file: processed_chunks.jsonl
    stats_file: processing_stats.json
  processed_dir: rag_system/data/processed
  raw_dir: rag_system/data/raw

# youtube:
#   api_key: "AIzaSyCZomDT0LCOEmUok4GnsA0txThR76Md9hU"  # Replace with your actual API key
#   max_results: 3
#   max_transcript_tokens: 2500


youtube:
  search_api_key: "AIzaSyCnMBnx4l3x5gWv-puVErKgwGrTAKHmFAY"  # YouTube Data API key for searching videos
  transcript_api_key: "SG2t3x5HGEjqzn217xnHFo76"  # SearchAPI.io API key for fetching transcripts
  max_results: 2  # Number of videos to fetch




generation:
  history_window: 5
  model:
    name: "mistralai/Mistral-7B-Instruct-v0.3"
    path: null  # Uses Hugging Face cache
  parameters:
    do_sample: true
    max_new_tokens: 1024
    quantize: null
    repetition_penalty: 1.1
    temperature: 0.6
    top_k: 70
  prompt:
    default_prompt_file: rag_prompt.txt
    max_context_length: 16384
    style: movie_savvy
    template_dir: generation/prompt_templates

performance:
  cache_embeddings: true
  cache_retrievals: false
  device: cuda
  max_memory_mb: 8192
  multiprocessing: false
  num_workers: 4

pipeline:
  batch_size: 1
  logging:
    level: INFO
    log_dir: output/logs
    log_file: rag_pipeline.log
  output:
    result_format: json
    results_dir: output/results
    save_intermediate: true
  timeout: 300

retrieval:
  embedding_dimension: 1024
  embedding_model: intfloat/e5-large-v2
  index:
    index_file: index.bin
    metadata_file: index_metadata.json
    save_dir: retrieval/index
    type: faiss
  max_retrieved_tokens: 4000
  similarity_threshold: 0.6
  top_k: 8
  web_search:
  priority_threshold: 0.5  # Similarity threshold for web search fallback
  max_web_results: 5
  web_content_length: 1000
  explicit_web_keywords:
    - "latest"
    - "current"
    - "recent"
    - "today"
    - "near"
    - "closest"
    - "book"
    - "where can I"
    - "location"
    - "nearby"
    - "available at"



system:
  description: Movie-savvy RAG system for entertainment queries
  name: Entertainment RAG System
  version: '1.2'

validation:
  metrics:
  - retrieval_time
  - generation_time
  - total_time
  - relevance_score
  test_queries:
  - Find anime similar to Berserk with dark themes
  - Compare Monkey D. Luffy and Eren Yeager character development
  - 'How does Pushpa Raj evolve in Pushpa 2: The Rule'